# Generated by Django 4.2.5 on 2023-09-29 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='locations',
            name='amenities',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='locations',
            name='avgAmen',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='locations',
            name='avgClean',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='locations',
            name='avgNoise',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='locations',
            name='nearPlaces',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='locations',
            name='hours',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='locations',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='locations',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='locations',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='locations',
            name='website',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
