# Generated by Django 4.2.5 on 2023-10-04 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='image',
            field=models.ImageField(blank=True, upload_to='tutor_images/'),
        ),
    ]
