# Generated by Django 4.2.5 on 2023-10-06 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_locationreviews_ammenitiesrating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locationreviews',
            old_name='ammenitiesRating',
            new_name='amenitiesRating',
        ),
    ]
