# Generated by Django 4.2.5 on 2023-10-08 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_uos_uoscomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uoscomment',
            name='SID',
        ),
        migrations.AddField(
            model_name='uoscomment',
            name='commenterSID',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uoscomment',
            name='uos',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='myapp.uos'),
        ),
    ]
