# Generated by Django 4.2.5 on 2023-10-08 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_uoscomment_sid_uoscomment_commentersid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
    ]
