# Generated by Django 4.2.5 on 2023-10-10 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationreviews',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_reviews', to='myapp.locations'),
        ),
    ]
