# Generated by Django 4.2.5 on 2023-10-10 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='image',
            field=models.ImageField(blank=True, upload_to='location_images/'),
        ),
    ]
