# Generated by Django 4.2.5 on 2023-10-10 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_locations_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='amenities_images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='locations',
            name='amenities',
        ),
        migrations.AddField(
            model_name='locations',
            name='amenities',
            field=models.ManyToManyField(blank=True, to='myapp.amenity'),
        ),
    ]
