# Generated by Django 4.2.5 on 2023-10-13 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_amenity_remove_locations_amenities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='nearby',
            field=models.ManyToManyField(blank=True, to='myapp.locations'),
        ),
    ]
