# Generated by Django 4.2.5 on 2023-10-13 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_locations_nearby'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='image',
            field=models.ImageField(blank=True, upload_to='location_images/'),
        ),
    ]
