# Generated by Django 4.2.5 on 2023-10-12 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0018_remove_locationreviews_reviewersid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uoscomment',
            name='commenterSID',
        ),
        migrations.AddField(
            model_name='uoscomment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='uoscomment',
            name='uos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uos_comment', to='myapp.uos'),
        ),
    ]
