# Generated by Django 4.2.5 on 2023-10-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_remove_uoscomment_commentersid_uoscomment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uoscomment',
            name='reports',
            field=models.IntegerField(default=0),
        ),
    ]
