# Generated by Django 4.2.5 on 2023-10-13 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_amenity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locations',
            name='amenities',
        ),
        migrations.AddField(
            model_name='locations',
            name='amenities',
            field=models.ManyToManyField(blank=True, to='myapp.amenity'),
        ),
    ]
