# Generated by Django 4.2.5 on 2023-10-13 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_locationreviews_user'),
        ('myapp', '0021_merge_20231013_0440'),
    ]

    operations = [
    ]
