# Generated by Django 4.2.5 on 2023-10-13 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_remove_locations_amenities_locations_amenities'),
        ('myapp', '0022_merge_20231013_0446'),
    ]

    operations = [
    ]
