# Generated by Django 4.2.5 on 2023-10-13 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_merge_20231013_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationreviews',
            name='reviewerSID',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
