# Generated by Django 4.2.5 on 2023-10-13 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_locationreviews_reviewersid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationreviews',
            name='reviewerSID',
        ),
    ]
