# Generated by Django 4.2.5 on 2023-10-14 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0025_remove_locationreviews_reviewersid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationreviews',
            name='likes',
        ),
        migrations.CreateModel(
            name='likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rev', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rev_like', to='myapp.locationreviews')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_like', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='locationreviews',
            name='like',
            field=models.ManyToManyField(related_name='rev_likes', through='myapp.likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
