# Generated by Django 4.2.5 on 2023-10-16 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0026_remove_locationreviews_likes_likes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationreviews',
            name='reports',
        ),
        migrations.CreateModel(
            name='reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rev_rep', to='myapp.locationreviews')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_rep', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='locationreviews',
            name='report',
            field=models.ManyToManyField(related_name='rev_reports', through='myapp.reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
