# Generated by Django 4.2.5 on 2023-10-16 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0027_remove_locationreviews_reports_reports_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uoscomment',
            name='reports',
        ),
        migrations.CreateModel(
            name='UoSRep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uos_rep', to='myapp.uoscomment')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uos_rep', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='uoscomment',
            name='report',
            field=models.ManyToManyField(related_name='uos_reports', through='myapp.UoSRep', to=settings.AUTH_USER_MODEL),
        ),
    ]
