# Generated by Django 4.2.5 on 2023-10-16 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_remove_uoscomment_reports_uosrep_uoscomment_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='avgOverall',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
