# Generated by Django 4.2.5 on 2023-10-27 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_locations_avgoverall'),
    ]

    operations = [
        migrations.AddField(
            model_name='uos',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
